config/routes.rb
ScheduleMiner::Application.routes.draw do
  get "users/index"

  get "schedule/index"

  get "static/index"
  get 'static/update'
  get 'static/builder' => 'static#builder', as: 'builder'

  match 'update_schedules' => 'schedules#new'
  match 'user_profile' => 'users#index'
  match 'user_edit' => 'users#edit'

  resources :departments

  resources :schedules do
      get 'add/:section_id' => 'schedules#add', as: 'add'
      get 'remove/:section_id' => 'schedules#remove', as: 'remove'
      get 'duplicate/:section_id' => 'schedules#duplicate', as: 'duplicate'
  end

  resources :users

  resources :teachers

  resources :buildings
  
  resources :courses do
    resources :sections
  end

  root to: 'static#index', as: 'static'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
	has_and_belongs_to_many :sections, uniq: true
	belongs_to :user

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_filter :authenticate_user!

  def index
  	@schedules = Schedule.find_all_by_user_id(@current_user.uid)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sections }
    end
  end

  def create
    @schedule = Schedule.new(params[:schedule])
    @schedule.user_id = @current_user.uid

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render json: @schedule, status: :created, location: @schedule }
      else
        format.html { render action: "new" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @schedule = Schedule.find(params[:id])


    respond_to do |format|
      if @schedule.update_attributes(params[:schedule])
        format.html { redirect_to @schedule, notice: 'Department was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @schedule = Schedule.find(params[:id])
    @schedule.destroy

    respond_to do |format|
      format.html { redirect_to schedules_url }
      format.json { head :no_content }
    end
  end

  def show
    @schedule = Schedule.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @schedule }
    end

  end

  def new
    @schedule = Schedule.new

    respond_to do |format|
     format.html # new.html.erb
     format.json { render json: @course }
    end
  end

  def edit
    @schedule = Schedule.find(params[:id])
  end

  def add
    schedule = Schedule.find(params[:schedule_id])
    section = Section.find(params[:section_id])

    respond_to do |format|
      if (schedule.sections << section)
        format.html { redirect_to schedule, notice: 'Successfully added section to schedule.' }
        format.json { render json: schedule, status: :created, location: schedule }
      else
        format.html { redirect_to schedule, notice: 'Section already exists in that schedule.' }
        format.json { render json: schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove
    schedule = Schedule.find(params[:schedule_id])
    section = Section.find(params[:section_id])

    respond_to do |format|
      if (schedule.sections.delete(section))
        format.html { redirect_to schedule, notice: 'Successfully removed section from the schedule.' }
        format.json { render json: schedule, status: :created, location: schedule }
      else
        format.html { redirect_to schedule, notice: 'Section doesnt exist in this schedule.' }
        format.json { render json: schedule.errors, status: :unprocessable_entity }
      end
    end 
  end

  def duplicate
    old.schedule = Schedule.find(params[:schedule_id])

    respond_to do |format|
        if (neW.schedule = Schedule.new(old.schedule.attributes))
        format.html { redirect_to schedule, notice: 'Successfully dupliacted schedule.' }
        format.json { render json: schedule, status: :created, location: schedule }
      else
        format.html { redirect_to schedule, notice: 'Can not duplicate schedule.' }
        format.json { render json: schedule.errors, status: :unprocessable_entity }
      end
    end
  end

end

app/helpers/schedule_helper.rb
module ScheduleHelper
end

app/views/schedules/_form.html.erb
<%= form_for(@schedule) do |f| %>
  <% if @schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% @schedule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/schedules/add.html.erb
<h2>SCHEDLSJFLS</h2>

app/views/schedules/destroy.html.erb
<h1>Schedule#index</h1>
<p>Find me in app/views/schedule/index.html.erb</p>

app/views/schedules/edit.html.erb
<% content_for :title do %>Editing schedule<% end %>

<%= render 'form' %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<!DOCTYPE html>
<% content_for :title do %>Schedules<% end %>


<body>
<table class="table">
  <tr>
    <th>Name</th>
    <th colspan="3">Settings</th>
  </tr>
<% @schedules.each do |schedule| %>
  <tr>
    <td><%= link_to schedule.name, schedule %></td>
    <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
    <td><%= link_to 'Remove', schedule, confirm: 'Are you sure?', method: :delete %></td>
    <td><%= link_to 'Duplicate', schedule %></td>


  </tr>
<% end %>
</table>

<br />

<%= link_to 'New schedule', new_schedule_path, class: "button radius" %>
</body>
</html>

app/views/schedules/new.html.erb
<% content_for :title do %>New schedule<% end %>

<!--<%= render 'form' %>-->
<hr /><br />
<form class="input-form" style="margin-bottom:50px">
	<div class="input-group" style="width:350px">
  		<span class="input-group-addon">Name:</span>
  		<input type="text" class="form-control" name="Name">
  		<span class="input-group-btn">
  			<button type="submit" id="create_schedule" class="btn btn-default">Create</button>
  		</span>
  	</div>
</form>

<button type="button" id="back_btn" class="btn btn-primary" onClick="location.href='/schedules'">Back</button>

<%= javascript_include_tag "hide_new" %>

app/views/schedules/show.html.erb
<% content_for :title do %><%= @schedule.name %><% end %>
<h2><%= @schedule.name %></h2>
<p id="notice"><%= notice %></p>

<%= render partial: 'shared/sections', locals: {sections: @schedule.sections} %>

<table>
	<td><%= link_to 'Back', courses_path %></td>
	<td><%= link_to 'Edit', edit_schedule_path %></td>
</table>

app/views/schedules/update.html.erb
<h1>Schedule#index</h1>
<p>Find me in app/views/schedule/index.html.erb</p>