config/routes.rb
ScheduleMiner::Application.routes.draw do
  get "users/index"

  get "schedule/index"

  get "static/index"
  get 'static/update'
  get 'static/builder' => 'static#builder', as: 'builder'

  match 'update_schedules' => 'schedules#new'
  match 'user_profile' => 'users#index'
  match 'user_edit' => 'users#edit'

  resources :departments

  resources :schedules do
      get 'add/:section_id' => 'schedules#add', as: 'add'
      get 'remove/:section_id' => 'schedules#remove', as: 'remove'
      get 'duplicate/:section_id' => 'schedules#duplicate', as: 'duplicate'
  end

  resources :users

  resources :teachers

  resources :buildings
  
  resources :courses do
    resources :sections
  end

  root to: 'static#index', as: 'static'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :sections, foreign_key: 'building_code', primary_key: 'code'
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @buildings }
    end
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
    @building = Building.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/new
  # GET /buildings/new.json
  def new
    @building = Building.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @building }
    end
  end

  # GET /buildings/1/edit
  def edit
    @building = Building.find(params[:id])
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(params[:building])

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render json: @building, status: :created, location: @building }
      else
        format.html { render action: "new" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /buildings/1
  # PUT /buildings/1.json
  def update
    @building = Building.find(params[:id])

    respond_to do |format|
      if @building.update_attributes(params[:building])
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building = Building.find(params[:id])
    @building.destroy

    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row collapse">
    <div class="small-3 columns">
      <%= f.label :code %>
    </div>
    <div class="small-9 columns"><%= f.text_field :code %></div>
  </div>
  <div class="row collapse">
    <div class="small-3 columns"><%= f.label :name %></div>
    <div class="small-9 columns"><%= f.text_field :name %></div>
  </div>
  <div class="row collapse">
    <div class="small-9 small-offset-3 columns"><%= f.submit %></div>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<% content_for :title do %>Buildings<% end %>

<table>
  <tr>
    <th>Code</th>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @buildings.each do |building| %>
  <tr>
    <td><%= building.code %></td>
    <td><%= link_to building.name, building %></td>
    <td><%= link_to 'Edit', edit_building_path(building) %></td>
    <td><%= link_to 'Remove', building, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Building', new_building_path, class: "button radius" %>

app/views/buildings/new.html.erb
<% content_for :title do %>New building<% end %>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<% content_for :title do %><%= @building.name %> (<%= @building.code %>)<% end %>

<p id="notice"><%= notice %></p>

<%= render partial: 'shared/sections', locals: {sections: @building.sections} %>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>