config/routes.rb
ScheduleMiner::Application.routes.draw do
  get "users/index"

  get "schedule/index"

  get "static/index"
  get 'static/update'
  get 'static/builder' => 'static#builder', as: 'builder'

  match 'update_schedules' => 'schedules#new'
  match 'user_profile' => 'users#index'
  match 'user_edit' => 'users#edit'

  resources :departments

  resources :schedules do
      get 'add/:section_id' => 'schedules#add', as: 'add'
      get 'remove/:section_id' => 'schedules#remove', as: 'remove'
      get 'duplicate/:section_id' => 'schedules#duplicate', as: 'duplicate'
  end

  resources :users

  resources :teachers

  resources :buildings
  
  resources :courses do
    resources :sections
  end

  root to: 'static#index', as: 'static'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  has_and_belongs_to_many :sections
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController

  # GET /teachers
  # GET /teachers.json
  def index
    # Prefetch teacher count to avoid a bazillion on-demand joins.
    @teachers = Teacher.order('teachers.name').joins(:sections).select('teachers.*, COUNT(sections_teachers.section_id) `sections_count`').group('teachers.id')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teachers }
    end
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/new
  # GET /teachers/new.json
  def new
    @teacher = Teacher.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @teacher }
    end
  end

  # GET /teachers/1/edit
  def edit
    @teacher = Teacher.find(params[:id])
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(params[:teacher])

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render json: @teacher, status: :created, location: @teacher }
      else
        format.html { render action: "new" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teachers/1
  # PUT /teachers/1.json
  def update
    @teacher = Teacher.find(params[:id])

    respond_to do |format|
      if @teacher.update_attributes(params[:teacher])
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher = Teacher.find(params[:id])
    @teacher.destroy

    respond_to do |format|
      format.html { redirect_to teachers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/teachers/_form.html.erb
<%= form_for(@teacher) do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<% if user_has? :admin %>
<% content_for :title do %>Editing teacher<% end %>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>
<%else%>
<h1 style="text-align: center">PERMISSION DENIED</h1>
<p style="text-align: center">You do not have permission to view this page</p>
<%end%>

app/views/teachers/index.html.erb
<% content_for :title do %>Teachers<% end %>

<% teachers_chunked = @teachers.group_by {|teacher| teacher.name.split[-1][0]} %>

<% teachers_chunked.keys.sort.each do |letter| %>

  <div class="container">
    <div class="row top-buffer">
      <!-- <ul class="large-block-grid-4"> -->
      <!-- <div class="flexcontainer"> -->
      <h2 class="col-md-1"><%= letter.upcase %></h2>
      <div class="row col-md-11">
        <% teachers_chunked[letter].sort_by {|teacher| teacher.name.split[-1]}.each do |teacher| %>
          <div class="teacher-button">
          <%= link_to teacher_path(teacher), class: "btn btn-default" do %>
            <%= teacher.name %>
            <span class="badge pull-radius"><%= teacher.sections_count %></span>
          <% end %>
          </div>
        <% end %>
      </div>
      <!-- </div> -->
      <!-- </ul> -->
    </div>
  </div>
<% end %>

<br />
<% if user_has? :admin %>
<%= link_to 'New Teacher', new_teacher_path, class: "button radius" %>
<% end %>

app/views/teachers/new.html.erb
<% if user_has? :admin %>
<% content_for :title do %>New teacher<% end %>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>
<% else %>
<h1 style="text-align: center">PERMISSION DENIED</h1>
<p style="text-align: center">You do not have permission to view this page</p>
<% end %>

app/views/teachers/show.html.erb
<% content_for :title do %><%= @teacher.name %><% end %>
<p id="notice"><%= notice %></p>

<%= render partial: 'shared/sections', locals: {sections: @teacher.sections} %>
<% if user_has? :admin %>
<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<% end %>
<%= link_to 'Back', teachers_path %>