config/routes.rb
ScheduleMiner::Application.routes.draw do
  get "users/index"

  get "schedule/index"

  get "static/index"
  get 'static/update'
  get 'static/builder' => 'static#builder', as: 'builder'

  match 'update_schedules' => 'schedules#new'
  match 'user_profile' => 'users#index'
  match 'user_edit' => 'users#edit'

  resources :departments

  resources :schedules do
      get 'add/:section_id' => 'schedules#add', as: 'add'
      get 'remove/:section_id' => 'schedules#remove', as: 'remove'
      get 'duplicate/:section_id' => 'schedules#duplicate', as: 'duplicate'
  end

  resources :users

  resources :teachers

  resources :buildings
  
  resources :courses do
    resources :sections
  end

  root to: 'static#index', as: 'static'
  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie9" lang="en"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
 <meta charset="utf-8" />

 <!-- Uncomment to make IE8 render like IE7 -->
 <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

 <!-- Set the viewport width to device width for mobile -->
 <meta name="viewport" content="width=device-width, initial-scale=1.0" />

 <title><%= content_for?(:title) ? yield(:title) + ' — ' : '' %>Schedule Miner</title>
 <%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Exo+2:400,100,100italic,400italic,700,700italic' %>
 <%= stylesheet_link_tag    "application" %>
 <%= csrf_meta_tags %>
 <script type="text/javascript">../../assets/javascript/bootstrap-hover-dropdown.js</script>
</head>

<body>

  <nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Schedule Miner</a>
    </div>

    <!-- Collect the nav links, forms, and other cmontent for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><div class="dropdown" style="margin-top:10px;">
        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-hover="dropdown">
        Browse
        <span class="caret"></span>
        </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
          <li role="presentation"><%= navbar_controller_entry "Courses", courses_path %>
          <li role="presentation"><%= navbar_controller_entry "Departments", departments_path %>
          </li>
          <li role="presentation"><%= navbar_controller_entry "Schedules", schedules_path %></li>
        <li role="presentation"><%= navbar_controller_entry "Teachers", teachers_path %></li>
        
        </div></li>
      </ul>
        <ul class="nav navbar-nav">
          <li><%= link_to "Builder", builder_path %></li>
        </ul>
      <form id="Search_button" class="navbar-form navbar-right" role="search">
       <input type="search" placeholder="Search">
      </form>
            <ul class="nav navbar-nav navbar-right">
        <li>
          <li class="divider"></li>
          <% if current_user %>
            <li class="navbar-text"><%= current_user.first_name.gsub(/\s.+/, '') %></li>
            <li class="divider"></li>
            <li><%= link_to 'Sign Out', signout_path %></li>
          <% else %>
            <li><%= link_to "Sign In", "/auth/google_oauth2" %></li>
          <% end %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </nav>
  <div class="container">
    <div class="row">
    <div class='col-md-4 col-md-offset-4'>
      <% flash.each do |name, msg| %>
      <div class="alert alert-success fade in">
        <!-- <%= content_tag :div, msg, id: "flash_#{name}" %> -->
        <%= msg %>
        <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
      </div>
      <% end %>
    </div>
    </div>
  </div>
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <% if content_for?(:title) %><h1><%= yield(:title) %></h1><% end %>
        <%= yield %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12" id="create_schedules_btn">
        <div><%= link_to 'Create Schedules', update_schedules_path, {class: "btn btn-success btn-lrg btn-block"}%> </div>
      </div>
    </div>
  </div>

  <%= javascript_include_tag "application" %>
</body>
</html>